Create Patient Service and Implement CRUD operations
projecttacoma/bulk-export-server pull request #45
Opened 2024-06-18 18:35 UTC by cgolemme

# Summary

This PR adds endpoints to the bulk-export-server to handle operations related to Patients. Adds operations to create, get and update patients in the server.

## New behavior

bulk-export-server now has CRUD operations for Patients
- `GET` : `[host]/Patient`
- `GET` : `[host]/Patient/[patientId]`
-  `POST` : `[host]/Patient`
-  `PUT` : `[host]/Patient/[patientID`

## Code changes
- `.eslintrc.json` and `.prettierignore` were changed to add `ecqm-content-r4-2021` to the excluded folders because they were causing warnings
- `src/server/app.js` was changed to add the endpoints to the server
- `src/services/group.service.js` updated some comments
- `src/services/patient.service.js` was created to implement functions that will interact with the database to fulfill the CRUD operations requested when a user accesses the endpoints for Patients
- `test/fixtures/updatedTestPatient.json` was created to test the Put endpoint by updating the gender field from the testPatient.json file
- `test/services/patient.service.test.js` are tests for the patient.service.js operations that follows closely from the `group.service.test.js` file.

# Testing guidance
- run `npm run check`
- Check that prettier and eslint cause no errors
- Check that all the tests pass

2024-06-19 15:06 UTC, elsaperelli approved these changes
Lgtm!

The only thing I would change in the future (not a big deal for this one at all) but just make sure that you include in the testing guidance to try out the new endpoints in Insomnia! (This should be kinda obvious but good to add)

2024-06-19 15:19 UTC, hossenlopp requested changes
The listing of all patients is returning a JSON Array this should be a `searchset` Bundle instead. See https://hl7.org/fhir/R4/http.html#search for more info.

Additionally we should have the internal mongo `_id`s projected out of the responses.

2024-06-19 19:38 UTC, cgolemme commented
I made the requested changes. One potentially weird thing that I did was call `const found = await findResourceById(request.params.groupId, 'Group');` in the group and patient delete functions in order to correctly return the 404 that we want because there is nowhere in the call stack of `removeReasource` that could throw an error the resource to remove is not found.

2024-06-19 20:14 UTC, elsaperelli requested changes
Just one small comment but otherwise almost good to go!

2024-06-19 20:14 UTC, elsaperelli commented on src/util/mongo.controller.js
> +  options.projection['_id'] = 0;
I am not sure if we need to pass in the projection and then set it again? Honestly seems like we could probably even get rid of the `options = {}` input (I know that was already there but looks like it isn't even needed lol) and then you can just do `const results = collection.find(query, { projection: { _id: 0 } });` unless I am missing something (very possible).

2024-06-20 13:33 UTC, elsaperelli approved these changes
Lgtm! Way to be flexible!!

2024-06-20 20:05 UTC, hossenlopp approved these changes

2024-06-20 20:05 UTC, merged