Updates for validation
projecttacoma/bulk-export-server pull request #53
Opened 2024-12-06 18:33 UTC by lmd59

# Summary
Update the qpp_qicore.yaml file to pass qicore validation

## New behavior
Generated synthea files pass validation (with a few potential exceptions).

## Code changes
- Adds or updates flexporter instructions for DeviceRequest, AdverseEvent, and Task

# Testing guidance
- Export files from synthea

2024-12-12 16:24 UTC, elsaperelli requested changes
One question:
1. When I ran the validator, it looks like I got errors with `.recorded` attributes on Procedure and Immunization resources? Is this expected?

Two suggestions:

1. I think the `-ig` parameter in the PR description is wrong- I think it should be `-ig hl7.fhir.us.qicore#4.1.1`. Not a huge deal, but I mention this because maybe some super quick validator instructions could be added to the `synthea/README.md` here! Not totally necessary but may be useful info in the future.

2. IF you end up adding something brief to the README, I would add the `-html-output` parameter. This is something I found in the Validator docs [here](https://confluence.hl7.org/display/FHIR/Using+the+FHIR+Validator) and made my life a lot easier. I actually think you probably used this input, it just wasn't reflected in the description.

2024-12-12 18:27 UTC, elsaperelli commented
> One question:
> 
> 1. When I ran the validator, it looks like I got errors with `.recorded` attributes on Procedure and Immunization resources? Is this expected?
> 
> Two suggestions:
> 
> 1. I think the `-ig` parameter in the PR description is wrong- I think it should be `-ig hl7.fhir.us.qicore#4.1.1`. Not a huge deal, but I mention this because maybe some super quick validator instructions could be added to the `synthea/README.md` here! Not totally necessary but may be useful info in the future.
> 2. IF you end up adding something brief to the README, I would add the `-html-output` parameter. This is something I found in the Validator docs [here](https://confluence.hl7.org/display/FHIR/Using+the+FHIR+Validator) and made my life a lot easier. I actually think you probably used this input, it just wasn't reflected in the description.

Update:
1. No longer get that error! I needed to run the following command: `java -jar validator_cli.jar synthea/output/fhir/ -ig http://hl7.org/fhir/us/qicore/ImplementationGuide/hl7.fhir.us.qicore%7C4.1.1 -extension any -display-issues-are-warnings -sct us -html-output output.html -version 4.0.1` (Need the http url, not `hl7.fhir.us.qicore#4.1.1` AND `-version 4.0.1`)
2. I would still add something to the README so that we can keep track of the `-ig`, `-version`, `-html-output`, and `clear-tx-cache` inputs.

2024-12-12 18:27 UTC, elsaperelli approved these changes
Besides a suggestion to add a bit of information to the README, this is looking good to me!!

2024-12-12 20:41 UTC, hossenlopp approved these changes

2024-12-13 21:18 UTC, elsaperelli approved these changes
Thanks for adding that stuff to the README! I think future us will thank now us 😄 Lgtm!

2024-12-13 21:24 UTC, merged